runtime: python39

instance_class: F1

env_variables:
  DB_USERNAME: root
  DB_PASSWORD: 'Canavaro66'
  DB_HOST: '/cloudsql/dash-ma-382623:us-central1:dash-ma-mysql'
  DB_PORT: '3306'  # Replace with the appropriate port number for your database
  DB_NAME: loan_eligibility
  DB_CONNECTION_NAME: 'dash-ma-382623:us-central1:dash-ma-mysql'
  

entrypoint: gunicorn -b :$PORT wsgi:app

automatic_scaling:
  max_instances: 5

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

beta_settings:
  cloud_sql_instances: <CONNECTION_NAME>
